eureka:
  instance:
    hostname: n5-jwt-food.herokuapp.com
    homePageUrl: https://${eureka.instance.hostName}/
    home-page-url-path: https://${eureka.instance.hostName}
    non-secure-port-enabled: true
    non-secure-port: 80
    secure-port: 443
    secure-port-enabled: false
  client:
    serviceUrl:
      defaultZone: https://n5-service-discovery.herokuapp.com/